---
- name: Print variables
  debug:
    msg: "Installing {{ zookeeper_archive }} into {{ prefix }} using build dir {{ zookeeper_dir }}"

- name: Download tar.gz 
  get_url: 
    url: "http://apache.mirror.cdnetworks.com/zookeeper/zookeeper-{{ zookeeper_version }}/{{ zookeeper_archive }}"
    dest: "{{ build_dir }}/{{ zookeeper_archive }}"

- name: Unpack tarball
  unarchive:
    src: "{{ build_dir }}/{{ zookeeper_archive }}"
    dest: "{{ build_dir }}"
  
- name: Configure zookeeper
  command: chdir={{ zookeeper_dir }} ./configure --prefix {{ prefix }}

- name: Make and install zookeeper globably
  command: chdir={{ zookeeper_dir }} /usr/bin/make -j8 install
